version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: pug
    versions:
    - 3.0.0
